[[beginning-story]]
== 書籍の始まり

この書籍を書くことにしたのは、自分が運営する JSer.info にて、
http://jser.info/post/77696682011/es6-promises[あなたが読むべきJavaScript Promises | JSer.info] という記事を書いた事が始まりの一つです。

この記事を書く際にECMAScript6 Promisesについて色々調べながら書いていましたが、
最終的に扱いきれてない情報もありました。

- https://github.com/azu/jser.info/pull/17[あなたが読むべきPromises by azu · Pull Request #17 · azu/jser.info]

またこの時、電子書籍はどのようなワークフローで書かれているんだろう？ということに興味を持っていて、
それを学ぶには実際に電子書籍を書いてみるのが早いと思ったのも書き始めた理由の一つです。

一番最初に自分用の今後やりたいTodoを書いているリポジトリにIssueを立てることから始めました。

- https://github.com/azu/azu/issues/7[Promisesの薄い本 · Issue #7 · azu/azu]

電子書籍を書くにはどのフォーマットで書くのかを決めなければなりません。

以前、 http://the-little-book-of-busterjs.readthedocs.org/en/latest/[The little book of Buster.JS] という電子書籍を書いた際は、
Sphinx(reStructuredText)を使って書いていたため、今回は別の方法を取ってみようと考えました。

最初に候補にしたのは人気のあるMarkdownでした。
しかし、Markdownには外部ファイルを読み込んで埋め込む標準的な方法がありません。

The little book of Buster.JS を書いた時からサンプルコードにテストを書くことにしていたので、
外部ファイルを読み込む機能は必要なものでした。

拡張したMarkdownフォーマットを利用するのも良いですが、その時にAsciiDocというOreillyも使っているフォーマットがあることを思い出しました。
また、Asciidocのモダンな処理エンジンとして http://asciidoctor.org/[Asciidoctor] という実装があることを知り、
これを使ってみようと思い書き始めました。

つまり、主目的は電子書籍を書いてみたいという欲求で、サブ目的がES6 Promisesについて扱いきれなかったものを書く
というのがこの書籍を書き始めた理由です。