[[beginning-story]]
== 書籍の始まり

この書籍を書くことにしたのは、私自身が運営する JSer.info にて、
http://jser.info/post/77696682011/es6-promises[あなたが読むべきJavaScript Promises | JSer.info] という記事を書いた事が始まりの一つです。

この記事を書く際にECMAScript6 Promisesについて色々調べながら書いていましたが、
最終的に扱いきれてない情報もありました。

- https://github.com/azu/jser.info/pull/17[あなたが読むべきPromises by azu · Pull Request #17 · azu/jser.info]

またこの時、電子書籍はどのようなワークフローで書かれているんだろう？ということに興味を持っていて、
それを学ぶには実際に電子書籍を書いてみるのが早いと思ったのも書き始めた理由の一つです。

一番最初に自分用の今後やりたいTodoを書いているリポジトリにIssueを立てることから始めました。

- https://github.com/azu/azu/issues/7[Promisesの薄い本 · Issue #7 · azu/azu]

電子書籍を書くにはどのフォーマットで書くのかを決めなければなりません。

以前、 http://the-little-book-of-busterjs.readthedocs.org/en/latest/[The little book of Buster.JS] という電子書籍を書いた際は、
Sphinx(reStructuredText)を使って書いていたため、今回は別の方法を取ってみようと考えました。

最初に候補にしたのは人気のあるMarkdownでした。
しかし、Markdownには外部ファイルを読み込んで埋め込む標準的な方法がありません。

The little book of Buster.JS を書いた時からサンプルコードにテストを書くことにしていたので、
外部ファイルを読み込む機能は必要なものでした。

拡張したMarkdownフォーマットを利用するのも良いですが、その時にAsciiDocというOreillyも使っているフォーマットがあることを思い出しました。
また、Asciidocのモダンな処理エンジンとして http://asciidoctor.org/[Asciidoctor] という実装があることを知り、
これを使ってみようと思い書き始めました。

つまり、主目的は電子書籍を書いてみたいという欲求で、サブ目的がES6 Promisesについて扱いきれなかったものを書く
というのがこの書籍を書き始めた理由です。

== 書き始めのワークフロー

おおまかに書く内容と形式を決めましたが、
私は形から入るタイプなので、Asciidocで書くときにどのようなプロジェクト構造が良いのか悩んでいた記憶があります。

そのため、一番最初に書いたのは https://github.com/azu/promises-book/commit/bbf23086c5bbaf60bd9991b5b1a4229ce54dfb30[CONTRIBUTE.md] で、
コントリビュートガイドを書くという形でプロジェクトの構造がどうあるべきかについて決めていきました。

書籍の内容としては、Promiseの基本的な使い方、パターンをコード例中心に書いていくというおおまかな方針が決まっていたので、
それをより明確にするためにアウトラインを軽く固めていきました。

- https://github.com/azu/promises-book/pull/1[この書籍で扱う内容について by azu · Pull Request #1 · azu/promises-book]

アウトラインを固めていきつつ、書籍を書く上で一番こわかったのが飽きることだったので、
とりあえずでもいいから好きなセクションを書いていきました。

そのため、書いた順番はかなりバラバラで、第二章が最初の方に書いた内容が多いです。

多くのセクションは、最初にコンセプトなるサンプルコードとテストを書いて、
それに対する解説して文章を書いていくという方針で行っていたものが多かったと記憶しています。

