[[what-is-promise]]
== What Is Promise

まずPromiseとはそもそもどのようなものでしょうか?

Promiseは非同期処理を抽象化したオブジェクトとそれを操作する仕組みのことをいいます。
詳しくはこれから学んでいくとして、PromiseはJavaScriptで発見された概念ではありません。

最初に発見されたのは http://erights.org/elib/distrib/pipeline.html[E言語]におけるもので、
並列/並行処理におけるプログラミング言語のデザインの一種です。

このデザインをJavaScriptに持ってきたものが、この書籍で学ぶJavaScript Promiseです。
Promiseは、JavaScriptの仕様を決めるECMAScript 2015で導入され動作が定義されています。

一方、JavaScriptにおける非同期処理といえば、コールバックを利用する場合が多いと思います。

[source,javascript]
.コールバックを使った非同期処理の一例
----
getAsync("fileA.txt", (error, result) => { // <1>
    if (error) { // 取得失敗時の処理
        throw error;
    }
    // 取得成功の処理
});
----
<1> コールバック関数の引数には(エラーオブジェクト, 結果)が入る

Node.js等JavaScriptでのコールバック関数の第一引数には `Error` オブジェクトを渡すというルールを用いるケースがあります。

このようにコールバックでの非同期処理もルールが統一されていた場合、コールバック関数の書き方が明確になります。
しかし、これはあくまでコーディングルールであるため、異なる書き方をしても決して間違いではありません。

Promiseでは、このような非同期に対するオブジェクトとルールを仕様化して、
統一的なインターフェースで書くようになっており、それ以外の書き方は出来ないようになっています。

[source,javascript]
.Promiseを使った非同期処理の一例
----
const promise = getAsyncPromise("fileA.txt"); // <1>
promise.then((result) => {
    // 取得成功の処理
}).catch((error) => {
    // 取得失敗時の処理
});
----
<1> promiseオブジェクトを返す

非同期処理を抽象化したpromiseオブジェクトというものを用意し、
そのpromiseオブジェクトに対して成功時の処理と失敗時の処理の関数を登録するようにして使います。

コールバック関数と比べると何が違うのかを簡単に見ると、
非同期処理の書き方がpromiseオブジェクトのインターフェースに沿った書き方に限定されます。

つまり、promiseオブジェクトに用意されているメソッド(ここでは `then` や `catch`)以外は使えないため、
コールバックのように引数に何を入れるかが自由に決められるわけではなく、一定のやり方に統一されます。

この、Promiseという統一されたインターフェースがあることで、
そのインターフェースにおけるさまざまな非同期処理のパターンを形成することができます。

つまり、複雑な非同期処理等を上手くパターン化できるというのがPromiseの役割であり、
Promiseを使う理由の一つであるといえるでしょう。

それでは、実際にJavaScriptでのPromiseについて学んでいきましょう。

[NOTE] 
.Arrow Function `=>`
====

この書籍のサンプルコードはArrow FunctionなどECMAScript 2015で導入された構文を利用します。

Arrow Functionは、矢印のような `=>` （イコールと大なり記号）を使い、匿名関数を定義する構文です。
関数式と定義方法や使い方は同じです。

[source,javascript]
----
// 関数式の定義と実行
const fn = function(arg) {
    console.log("通常の関数定義, 引数:" + arg);
};
fn("引数");

// Arrow Functionの定義と実行
const arrowFunction = (arg) => {
    console.log("Arrow Functionでの関数定義, 引数:" + arg);
};
arrowFunction("引数");
----

通常の関数式と`=>`という記法を使う以外にも次のような特徴があります。

Arrow Functionには次のような特徴があります。

- 名前を付けることができない（常に匿名関数）
- `this` が静的に決定できる
- `function` キーワードに比べて短く書くことができる
- `new` できない（コンストラクタ関数ではない）
- `arguments` 変数を参照できない(Rest Parametersを代わりに利用する)

Arrow Functionを使うことで、コールバック関数を関数式に比べて短く簡潔に書くことができます。
そのため、この書籍ではArrow Functionをメインに利用しています。

Arrow Functionの詳細は https://jsprimer.net[JavaScript Primer] を参照してください。

- https://jsprimer.net/basic/function-declaration/#arrow-function[関数と宣言 · JavaScript Primer #jsprimer]

====
