[[what-is-promise]]
== What Is Promise

まずPromiseとはそもそも何でしょう?

Promiseは非同期処理を抽象化したオブジェクトとそれを操作する仕組みを提供するものの事を言います。
詳しくはこれから学んでいくとして、PromiseはJavaScriptで発見された概念ではありません。

最初に発見されたのは http://erights.org/elib/distrib/pipeline.html[E言語]におけるもので、
並列/並行処理におけるプログラミング言語のデザインの一種です。

JavaScriptにおける非同期処理といえば、コールバックを利用する場合が多いと思います。

[source,js]
.コールバックを使った非同期処理の一例
----
getAsync("fileA.txt", function(error, result){// <1>
    if(error){// 取得失敗時の処理
        throw error;
    }
    // 取得成功の処理
});
----
<1> コールバック関数の引数には(エラーオブジェクト, 結果)が入る

Node.js等JavaScriptでのコールバック関数の第一引数には`Error`オブジェクトを渡すという
ルールを用いるケースがあります。

このようにコールバックでの非同期処理もルールが統一されていた場合、
コールバック関数には何を書けばいいかが明確になります。
しかし、これはあくまでコーディングルールであるので、異なる書き方をしても決して間違いではありません。

Promiseでは、このような非同期に対するオブジェクトとルールを仕様化して、
Promiseを使った場合は常に統一的なインターフェースで書けるようしています。

[source,js]
.Promiseを使った非同期処理の一例
----
var promise = getAsyncPromise("fileA.txt"); // <1>
promise.then(function(result){
    // 取得成功の処理
}).catch(function(error){
    // 取得失敗時の処理
});
----
<1> promiseオブジェクトを返す

非同期処理を抽象化したpromiseオブジェクトというものを用意し、
そのpromiseオブジェクトに対して成功時の処理と失敗時の処理の関数を登録するようにして使います。

コールバック関数と比べると何か違うのかを簡単に見ると、
非同期処理の書き方がpromiseオブジェクトのインターフェースに沿った書き方に限定されます。

つまり、promiseオブジェクトに用意されてるメソッド(ここでは`then`や`catch`)以外は使えないため、
コールバックのように引数に何を入れるかが自由に決められるわけではなく、一定のやり方に統一されます。

この、Promiseという統一されたインターフェースがあることで、
そのインターフェースにおける様々な非同期処理のパターンが形成することが出来ます。

つまり、Promiseを学ぶ事で複雑な非同期処理等を上手くパターン化できるというのが、
Promiseの役割であり、Promiseを使う理由の一つであるといえるでしょう。