[[promise-api-reference]]
= Promises API Reference

[[promise.then]]
== Promise#then
[source,javascript]
----
promise.then(onFulfilled, onRejected);
----

[role="executable"]
[source,javascript]
.thenコード例
----
var promise = new Promise(function(resolve, reject){
    resolve("thenに渡す値");
});
promise.then(function (value) {
    console.log(value);
}, function (error) {
    console.error(error);
});
----

promiseオブジェクトに対してonFulfilledとonRejectedのハンドラを定義し、
新たなpromiseオブジェクトを作成して返す。

このハンドラはpromiseがresolve または rejectされた時にそれぞれ呼ばれる。

* 定義されたハンドラ内で返した値は、新たなpromiseオブジェクトのonFulfilledに対して渡される。
* 定義されたハンドラ内で例外が発生した場合は、新たなpromiseオブジェクトのonRejectedに対して渡される。

[[promise.catch]]
== Promise#catch
[source,javascript]
promise.catch(onRejected);

[role="executable"]
[source,javascript]
.catchのコード例
----
var promise = new Promise(function(resolve, reject){
    resolve("thenに渡す値");
});
promise.then(function (value) {
    console.log(value);
}).catch(function (error) {
    console.error(error);
});
----

`promise.then(undefined, onRejected)` と同等の意味を持つシンタックスシュガー。

[[Promise.resolve]]
== Promise.resolve
[source,javascript]
----
Promise.resolve(promise);
Promise.resolve(thenable);
Promise.resolve(object);
----

[role="executable"]
[source,javascript]
.Promise.resolveのコード例
----
var taskName = "task 1"
asyncTask(taskName).then(function (value) {
    console.log(value);
}).catch(function (error) {
    console.error(error);
});
function asyncTask(name){
    return Promise.resolve(name).then(function(value){
        return "Done! "+ value;
    });
}
----


受け取った値に応じたpromiseオブジェクトを返す。

どの場合でもpromiseオブジェクトを返すが、大きく分けて以下の3種類となる。

promiseオブジェクトを受け取った場合::
受け取ったpromiseオブジェクトをそのまま返す
thenableなオブジェクトを受け取った場合::
`then`を持つオブジェクトを新たなpromiseオブジェクトにして返す
その他の値(オブジェクトやnull等も含む)を受け取った場合::
その値でresolveされる新たなpromiseオブジェクトを作り返す

[[Promise.reject]]
== Promise.reject
[source,javascript]
Promise.reject(object)

[source,javascript]
.Promise.rejectのコード例
----
var failureStub = sinon.stub(xhr, "request").returns(Promise.reject(new Error("bad!")));
----

受け取った値でrejectされた新たなpromiseオブジェクトを返す。

Promise.rejectに渡す値は`Error`オブジェクトとすべきである。

また、Promise.resolveとは異なり、promiseオブジェクトを渡した場合も常に新たなpromiseオブジェクトを作成する。

[role="executable"]
[source,javascript]
----
var r = Promise.reject(new Error("error"));
console.log(r === Promise.reject(r));// false
----


[[Promise.all]]
== Promise.all
[source,javascript]
Promise.all(promiseArray);

[role="executable"]
[source,javascript]
.Promise.allのコード例
----
var p1 = Promise.resolve(1),
    p2 = Promise.resolve(2),
    p3 = Promise.resolve(3);
Promise.all([p1, p2, p3]).then(function (results) {
    console.log(results);  // [1, 2, 3]
});
----


新たなpromiseオブジェクトを作成して返す。

渡されたpromiseオブジェクトの配列が全てresolveされた時に、
新たなpromiseオブジェクトはその値でresolveされる。

どれかの値がrejectされた場合は、その時点で新たなpromiseオブジェクトはrejectされる。

渡された配列の値はそれぞれ`Promise.resolve`にラップされるため、
promiseオブジェクト以外が混在している場合も扱える。

[[Promise.race]]
== Promise.race
[source,javascript]
Promise.race(promiseArray);

[role="executable"]
[source,javascript]
.Promise.raceのコード例
----
var p1 = Promise.resolve(1),
    p2 = Promise.resolve(2),
    p3 = Promise.resolve(3);
Promise.race([p1, p2, p3]).then(function (value) {
    console.log(value);  // 1
});
----

新たなpromiseオブジェクトを作成して返す。

渡されたpromiseオブジェクトの配列のうち、
一番最初にresolve または rejectされたpromiseにより、
新たなpromiseオブジェクトはその値でresolve または rejectされる。
