[[promise-api-reference]]
= Promises API Reference

[[promise.then]]
[source,js]
promise.then(<onFulfilled>, <onRejected>);

promiseオブジェクトに対してonFulfilledとonRejectedのハンドラを定義する。
このハンドラはpromiseがresolve 又は rejectされた時にそれぞれ呼ばれる。

このメソッドは新たなpromiseオブジェクトを作成して返す。

* 定義されたハンドラ内で返した値は、新たなpromiseオブジェクトのonFulfilledに対して渡される。
* 定義されたハンドラ内で例外が発生した場合は、新たなpromiseオブジェクトのonRejectedに対して渡される。

[[promise.catch]]
[source,js]
promise.catch(onRejected);

`promise.then(undefined, onRejected)` と同等の意味を持つシンタックスシュガー。


[[Promise.resolve]]
[source,js]
Promise.resolve(promise);
Promise.resolve(thenable);
Promise.resolve(object);

受け取った値に応じたpromiseオブジェクトを返す。

どの場合でもpromiseオブジェクトを返すが、大きく分けて以下の3種類となる。

promiseオブジェクトを受け取った場合::
そのpromiseオブジェクトをそのまま返す
thenableなオブジェクトを受け取った場合::
`then`を持つオブジェクトを受け取り、新たなpromiseオブジェクトにして返す
その他の値(オブジェクトやnull等も含む)を受け取った場合::
その値がresolveされる新たなpromiseオブジェクトを作り返す

[[Promise.reject]]
[source,js]
Promise.rejct(object)

受け取った値でrejectされた新たなpromiseオブジェクトを返す。
Promise.rejctに渡す値は`Error`オブジェクトとすべきである。

また、Promise.resolveとは異なり、promiseオブジェクトを渡した場合も常に新たなpromiseオブジェクトを作成する。

[source,js]
----
var r = Promise.reject(new Error("error"));
r === Promise.reject(r);// false
----


[[Promise.all]]
[source,js]
Promise.all(promiseArray);

新たなpromiseオブジェクトを作成して返す。
渡されたpromiseオブジェクトの配列が全てresolveされた時に、
新たなpromiseオブジェクトはその値でresolveされる。

どれかの値がrejectされた場合は、その時点で新たなpromiseオブジェクトはrejectされる。

渡された配列の値はそれぞれ`Promise.resolve`にラップされるため、
promiseオブジェクト以外が混じっている場合も扱える。

[[Promise.race]]
[source,js]
Promise.race(promiseArray);

新たなpromiseオブジェクトを作成して返す。
渡されたpromiseオブジェクトの配列のうち、一番最初にresolve または rejectされた時に、
新たなpromiseオブジェクトはその値でresolveされる。





