[[ch2-promise-all]]
== Promise.all

先ほどの複数のXHRの結果をまとめたものを取得する処理は、 <<Promise.all, `Promise.all`>> を使うと次のように書くことが出来ます。

<<Promise.all, `Promise.all`>> は 配列を受け取り、
その配列に入っているpromiseオブジェクトが全てresolveされた時に、次の`.then`を呼び出します。

下記の例では、promiseオブジェクトはXHRによる通信を抽象化したオブジェクトといえるので、
全ての通信が完了(resolveまたはreject)された時に、次の`.then`が呼び出されます。

[source,js]
[[promise-all-xhr.js]]
.promise-all-xhr.js
----
include::embed/embed-promise-all-xhr.js[]
----

実行方法は <<xhr-promise.js, 前回のもの>> と同じで以下のようにして実行出来ます。

[source,js]
----
main().then(function (value) {
    console.log(value);
}).catch(function(error){
    console.log(error);
});
----

<<Promise.all, `Promise.all`>> を使うことで以下のような違いがあることがわかります。

* mainの処理がスッキリしている
* Promise.all は promiseオブジェクトの配列を扱っている

[source,js]
Promise.all([request.comment(), request.people()]);

というように処理を書いた場合は、`request.comment()` と `request.people()` は同時に実行されますが、
それぞれのpromiseの結果(resolve,rejectで渡される値)は、<<Promise.all, `Promise.all`>>に渡した配列の順番となります。

つまり、この場合に次の`.then`に渡される結果の配列は [comment, people]の順番になることが保証されています。

[source,js]
----
main().then(function (results) {
    console.log(results); // [comment, people]の順番
});
----

<<Promise.all, `Promise.all`>> に渡したpromiseオブジェクトが同時に実行されてるのは、
次のようなタイマーを使った例を見てみると分かりやすいです。

[source,js]
[[promise-all-timer.js]]
.promise-all-timer.js
----
include::embed/embed-promise-all-timer.js[]
----

`promisedMapping` に数値の配列を渡すと、
数値をそのまま`setTimeout`に設定したpromiseオブジェクトの配列を返す関数です。

[source,js]
promisedMapping([1, 2, 4, 8, 16, 32]);

この場合は、1,2,4,8,16,32 ms後にそれぞれresolveされるpromiseオブジェクトの配列を作って返します。

つまり、このpromiseオブジェクトの配列がすべてresolveされるには最低でも32msかかることがわかります。
実際に<<Promise.all, `Promise.all`>> で処理してみると 約32msかかる事がわかります。

この事から、<<Promise.all, `Promise.all`>> が一つづつ順番にやるわけではなく、
渡されたpromiseオブジェクトの配列を並列に実行してるという事がわかります。

[NOTE]
====
仮に逐次的に行われていた場合は、
1ms待機 -> 2ms待機 -> 4ms待機 -> ... -> 32ms待機 となるので、
全て完了するまで64ms程度かかる計算になります。

実際にPromiseを逐次的に処理したいケースについては第4章の<<promise-sequence, Promiseによる逐次処理>>を参照して下さい。
====