[[ch2-promise-all]]
== Promise.all

<<Promise.all, `Promise.all`>> は promiseオブジェクトの配列を受け取り、
その配列に入っているpromiseオブジェクトが全てresolveされた時に、次の `.then` を呼び出します。

先ほどの複数のXHRの結果をまとめて取得する処理は、 <<Promise.all, `Promise.all`>> を使うとシンプルに書くことができます。

先ほどの例の `fetchURL` はXHRによる通信を抽象化したpromiseオブジェクトを返しています。
`Promise.all` に通信を抽象化したpromiseオブジェクトの配列を渡すことで、
全ての通信が完了(FulfilledまたはRejected)した時に、次の `.then` を呼び出すことができます。

[role="executable"]
[source,javascript]
[[promise-all-xhr.js]]
.promise-all-xhr.js
----
include::embed/embed-promise-all-xhr.js[]
// 実行例
main().then((value) => {
    console.log(value);
}).catch((error) => {
    console.error(error);
});
----

実行方法は <<xhr-promise.js, 前回のもの>> と同じですね。
<<Promise.all, `Promise.all`>> を使うことで以下のような違いがあることがわかります。

* mainの処理がスッキリしている
* Promise.all は promiseオブジェクトの配列を扱っている

[source,javascript]
Promise.all([request.comment(), request.people()]);

というように処理を書いた場合は、`request.comment()` と `request.people()` は同時に実行されますが、
それぞれのpromiseの結果(resolve,rejectで渡される値)は、<<Promise.all, `Promise.all`>>に渡した配列の順番となります。

つまり、この場合に次の `.then` に渡される結果の配列は [comment, people]の順番になることが保証されています。

[source,javascript]
----
main().then((results) => {
    console.log(results); // [comment, people]の順番
});
----

<<Promise.all, `Promise.all`>> に渡したpromiseオブジェクトが同時に実行されてるのは、
次のようなタイマーを使った例を見てみると分かりやすいです。

[role="executable"]
[source,javascript]
[[promise-all-timer.js]]
.promise-all-timer.js
----
include::embed/embed-promise-all-timer.js[]
----

`timerPromisefy` は引数で指定したミリ秒後に、その指定した値でFulfilledとなる
promiseオブジェクトを返してくれます。

`Promise.all` に渡してるのは、それを複数作り配列にしたものですね。

[source,javascript]
----
const promises = [
    timerPromisefy(1),
    timerPromisefy(32),
    timerPromisefy(64),
    timerPromisefy(128)
];
----

この場合は、1, 32, 64, 128 ミリ秒後にそれぞれ `resolve` されます。

つまり、このpromiseオブジェクトの配列がすべてresolveされるには、最低でも128msかかることがわかります。
実際に<<Promise.all, `Promise.all`>> で処理してみると 約128msかかることがわかります。

このことから、<<Promise.all, `Promise.all`>> が一つづつ順番にやるわけではなく、
渡されたpromiseオブジェクトの配列を並列に実行してるということがわかります。

[NOTE]
====
仮に逐次的に行われていた場合は、
1ms待機 -> 32ms待機 -> 64ms待機 -> 128ms待機 となるので、
全て完了するまで225ms程度かかる計算になります。

実際にPromiseを逐次的に処理したいケースについては第4章の<<promise-sequence, Promiseによる逐次処理>>を参照して下さい。
====
