[[ch2-promise-resolve]]
== Promise.resolve

一般に `new Promise()` を使うことでpromiseオブジェクトを生成しますが、
それ以外にもpromiseオブジェクトを生成する方法があります。

ここでは、<<Promise.resolve, `Promise.resolve`>> と <<Promise.reject, `Promise.reject`>> について学びたいと思います。

=== new Promiseのショートカット

<<Promise.resolve, `Promise.resolve(value)`>> という静的メソッドは、
`new Promise()` のショートカットとなるメソッドです。

たとえば、 `Promise.resolve(42);` というのは下記のコードのシンタックスシュガーです。

[source,javascript]
----
new Promise((resolve) => {
    resolve(42);
});
----

結果的にすぐに `resolve(42);` と解決されて、次のthenの `onFulfilled` に設定された関数に `42` という値を渡します。

`Promise.resolve(value);` で返ってくる値も同様にpromiseオブジェクトなので、
以下のように続けて `.then` を使った処理を書くことができます。

[role="executable"]
[source,javascript]
----
Promise.resolve(42).then((value) => {
    console.log(value);
});
----

<<Promise.resolve,Promise.resolve>>は `new Promise()` のショートカットとして、
promiseオブジェクトの初期化時やテストコードを書く際にも活用できます。

=== Thenable

もう一つ `Promise.resolve` の大きな特徴として、<<Thenable,thenable>>なオブジェクトをpromiseオブジェクトに変換するという機能があります。

<<es-promises,ES Promises>>には<<Thenable,Thenable>>という概念があり、簡単にいえばpromiseっぽいオブジェクトのことを言います。

`.length` を持っているが配列ではないものをArray likeというのと同じで、
thenableの場合は `.then` というメソッドを持ってるオブジェクトを言います。

thenableなオブジェクトがもつ `then` は、Promiseのもつ `then` と同じような挙動を期待していて、
thenableなオブジェクトがもつ元々の `then` を上手く利用できるようにしpromiseオブジェクトに変換するという仕組みです。

どのようなものがthenableなのかというと、分かりやすい例では
https://api.jquery.com/jQuery.ajax/[jQuery.ajax()]の返り値もthenableです。

`jQuery.ajax()` の返り値は http://api.jquery.com/jQuery.ajax/#jqXHR[jqXHR Object] というもので、
このオブジェクトは `.then` というメソッドを持っているためです。

[source,javascript]
// このサンプルコードはjQueryをロードしている場所でないと動きません
$.ajax("https://httpbin.org/get");// => `.then` をもつオブジェクト

このthenableなオブジェクトを `Promise.resolve` ではpromiseオブジェクトにすることができます。

promiseオブジェクトにすることができれば、`then` や `catch` といった、
<<es-promises,ES Promises>>がもつ機能をそのまま利用することができるようになります。

[source,javascript]
.thenableをpromiseオブジェクトにする
----
// このサンプルコードはjQueryをロードしている場所でないと動きません
const promise = Promise.resolve($.ajax("https://httpbin.org/get"));// => promiseオブジェクト
promise.then((value) => {
    console.log(value);
});
----

[WARNING]
.jQueryとthenable
====
https://api.jquery.com/jQuery.ajax/[jQuery.ajax()]の返り値も `.then` というメソッドを持った http://api.jquery.com/jQuery.ajax/#jqXHR[jqXHR Object]で、
このオブジェクトは http://api.jquery.com/category/deferred-object/[Deferred Object] のメソッドやプロパティ等を継承しています。

しかし、jQuery 2.x以下では、このDeferred Objectは<<promises-aplus,Promises/A+>>や<<es-promises,ES Promises>>に準拠したものではありません。
そのため、Deferred Objectをpromiseオブジェクトへ変換できたように見えて、一部欠損する情報がでてしまうという問題があります。

この問題はjQueryの http://api.jquery.com/category/deferred-object/[Deferred Object] の `then` の挙動が違うために発生します。

そのため、`.then` というメソッドを持っていた場合でも、必ずES Promisesとして使えるとは限らないことは知っておくべきでしょう。

* http://www.html5rocks.com/ja/tutorials/es6/promises/#toc-lib-compatibility[JavaScript Promises: There and back again - HTML5 Rocks]
* http://domenic.me/2012/10/14/youre-missing-the-point-of-promises/[You&#39;re Missing the Point of Promises]

なお、jQuery 3.0からは、 http://api.jquery.com/category/deferred-object/[Deferred Object]や http://api.jquery.com/jQuery.ajax/#jqXHR[jqXHR Object]が<<promises-aplus,Promises/A+>>準拠へと変更されています。
そのため、上記で紹介されている `.then` の挙動が異なる問題は解消されています。

* https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/[jQuery 3.0 Final Released! | Official jQuery Blog]

====

`Promise.resolve` は共通の挙動である `then` だけを利用して、
さまざまなライブラリ間でのpromiseオブジェクトを相互に変換して使える仕組みを持っていることになります。

このthenableを変換する機能は、以前は `Promise.cast` という名前であったことからもその挙動が想像できるかもしれません。

ThenableについてはPromiseを使ったライブラリを書くとき等には知っておくべきですが、
通常の利用だとそこまで使う機会がないものかもしれません。

[NOTE]
====
ThenableとPromise.resolveの具体的な例を交えたものは
第4章の<<resolve-thenable,Promise.resolveとThenable>>にて詳しく解説しています。
====

`Promise.resolve` を簡単にまとめると、「渡した値でFulfilledされるpromiseオブジェクトを返すメソッド」と考えるのがいいでしょう。

また、Promiseの多くの処理は内部的に `Promise.resolve` のアルゴリズムを使って値をpromiseオブジェクトに変換しています。
