== new Promiseのショートカット

一般に `new Promise()` を使う事でpromiseオブジェクトを生成しますが、
それ以外にもpromiseオブジェクトを生成する方法があります。

この節では、<<Promise.resolve, `Promise.resolve`>> と <<Promise.reject, `Promise.reject`>> について学びたいと思います。

=== Promise.resolve

<<Promise.resolve, `Promise.resolve(value)`>> という静的メソッドは、
`new Promise()` のショートカットとなるメソッドです。

例えば、 `Promise.resolve(42)` というのは下記のコードのシンタックスシュガーです。

[source,js]
----
new Promise(function(resolve){
    resolve(42);
});
----

結果的にすぐに`resolve(42)`と解決されて、次のthenの`onFulfilled`に設定された関数に`42`という値を渡します。

<<Promise.resolve, `Promise.resolve(value)`>>の返す値も同様にpromiseオブジェクトなので、
以下のように `.then` を使った処理を書くことが出来ます。

[source,js]
----
Promise.resolve(42).then(function(value){
    console.log(value);
});
----


=== ThenableとPromise.resolve

<<Promise.resolve,Promise.resolve>>は`new Promise()`のショートカットとして使う事が出来るのは、
テストコードを書く際にも活用できますが、もう一つ大きな特徴を持っています。

<<ES6 Promises>>には<<Thenable,Thenable>>という概念があり、
thenableとは簡単にいえばpromiseっぽいオブジェクトの事を言います。
`.length`を持つけど配列じゃないものをArray likeとかというのと同じような話となります。

<<Thenable,thenable>>の場合は`.then`というメソッドを持ってるオブジェクトのことを言います。

////

どういうものがthenableなのかというと、分かりやすい例では
https://api.jquery.com/jQuery.ajax/[jQuery.ajax()]の返り値もthenableです。

[source,js]
$.ajax('/json/comment.json');// => `.then`を持つオブジェクト

////

このthenableなオブジェクトを<<Promise.resolve,Promise.resolve>>ではpromiseオブジェクトにすることが出来ます。
