[[promise-sequence]]
== Promiseによる逐次処理

第2章の<<ch2-promise-all, Promise.all>>では、
複数のpromiseオブジェクトをまとめて処理する方法について学びました。

しかし、`Promise.all` は全ての処理を並行に行うため、
Aの処理 が終わったら Bの処理 というような逐次的な処理を扱うことができません。

また、同じ2章の<<ch2-promise-and-array,Promiseと配列>>では、
効率的ではないですが、<<multiple-xhr.js,thenを連ねた書き方>>でそのような逐次処理を行っていました。

このセクションでは、Promiseを使った逐次処理の書き方について学んで行きたいと思います。

=== ループと逐次処理

<<multiple-xhr.js,thenを連ねた書き方>>では以下のような書き方でしたね。

[role="executable"]
[source,javascript]
----
include::../Ch2_HowToWrite/embed/embed-multiple-xhr.js[]
// 実行例
main().then((value) => {
    console.log(value);
}).catch((error) => {
    console.error(error);
});
----

この書き方だと、`request` の数が増える分 `then` を書かないといけなくなってしまいます。

そこで、処理を配列にまとめて、forループで処理していければ、数が増えた場合も問題無いですね。
まずはforループを使って先ほどと同じ処理を書いてみたいと思います。

[role="executable"]
[source,javascript]
[[promise-foreach-xhr.js]]
.promise-foreach-xhr.js
----
include::embed/embed-promise-foreach-xhr.js[]
// 実行例
main().then((value) => {
    console.log(value);
}).catch((error) => {
    console.error(error);
});
----

forループで書く場合、<<then-return-new-promise,コラム: thenは常に新しいpromiseオブジェクトを返す
>>や<<promise-and-method-chain,Promiseとメソッドチェーン>>で学んだように、
<<promise.then, Promise#then>> は新しいpromiseオブジェクトを返しています。

そのため、`promise = promise.then(task).then(pushValue);` というのは `promise` という変数に上書きするというよりは、
そのpromiseオブジェクトに処理を追加していくような処理になっています。

しかし、この書き方だと一時変数として `promise` が必要で、処理の内容的にもあまりスッキリしません。

このループの書き方は `Array.prototype.reduce` を使うともっとスマートに書くことができます。

=== Promise chainとreduce

`Array.prototype.reduce` を使って書き直すと以下のようになります。

[role="executable"]
[source,javascript]
[[promise-reduce-xhr.js]]
.promise-reduce-xhr.js
----
include::embed/embed-promise-reduce-xhr.js[]
// 実行例
main().then((value) => {
    console.log(value);
}).catch((error) => {
    console.error(error);
});
----

`main` 以外の処理はforループのものと同様です。

`Array.prototype.reduce` は第二引数に初期値を入れることができます。
つまりこの場合、最初の `promise` には `Promise.resolve()` が入り、
そのときの `task` は `request.comment` となります。

reduceの中で `return` したものが、次のループで `promise` に入ります。
つまり、`then` を使って作成した新たなpromiseオブジェクトを返すことで、
forループの場合と同じように<<promise-chain, Promise chain>>を繋げることができます。

[NOTE]
=====
`Array.prototype.reduce` については詳しくは以下を参照して下さい。

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce[Array.prototype.reduce() - JavaScript | MDN]
* https://azu.github.io/slide/JSGohan/reduce.html[Array.prototype.reduce Dance]
=====

forループと異なる点は、一時変数としての `promise` が不要になることに伴い、
`promise = promise.then(task).then(pushValue);` という不格好な書き方がなくなる点が大きな違いだと思います。

`Array.prototype.reduce` とPromiseの逐次処理は相性がよいので覚えておくといいのですが、
初めて見た時にどのような動作をするのかがまだ分かりにくいという問題があります。

そこで、処理するTaskとなる関数の配列を受け取って逐次処理を行う
`sequenceTasks` というものを作ってみます。

以下のように書くことができれば、`tasks` が順番に処理されていくことが関数名から見て分かるようになります。

[source,javascript]
----
const tasks = [request.comment, request.people];
sequenceTasks(tasks);
----

=== 逐次処理を行う関数を定義する

基本的には、<<promise-reduce-xhr.js,reduceを使ったやり方>>を関数として切り離せばいいだけですね。

[source,javascript]
[[promise-sequence.js]]
.promise-sequence.js
----
include::embed/embed-promise-sequence.js[]
----

一つ注意点として、`Promise.all` 等と違い、引数に受け取るのは関数の配列です。

なぜ、渡すのがpromiseオブジェクトの配列ではないのかというと、
promiseオブジェクトを作った段階ですでにXHRが実行されている状態なので、
それを逐次処理しても意図とは異なる動作になるためです。

そのため `sequenceTasks` では関数(promiseオブジェクトを返す)の配列を引数に受け取ります。

最後に、`sequenceTasks` を使って最初の例を書き換えると以下のようになります。

[role="executable"]
[source,javascript]
[[promise-sequence-xhr.js]]
.promise-sequence-xhr.js
----
include::embed/embed-promise-sequence-xhr.js[]
// 実行例
main().then((value) => {
    console.log(value);
}).catch((error) => {
    console.error(error);
});
----

`main()` の中がかなりスッキリしたことが分かります。

このようにPromiseでは、逐次処理ということをするのに色々な書き方ができると思います。

* <<multiple-xhr.js, thenをその場に並べた書き方>>
* <<promise-foreach-xhr.js, forループを使った書き方>>
* <<promise-reduce-xhr.js, reduceを使った書き方>>
* <<promise-sequence.js, 逐次処理する関数を分けた書き方>>

さらに、ここではまだ紹介していませんが、<<chapter5-async-function, Async Function>>を使う方法もあります。

しかし、これはJavaScriptで配列を扱うのにforループや `forEach` 等、色々やり方があるのと本質的には違いはありません。
そのため、Promiseを扱う場合も処理をまとめられるところは小さく関数に分けて、実装していくのがいいといえるでしょう。

=== まとめ

このセクションでは、<<Promise.all, `Promise.all`>>とは違い、
一つづつ順番に処理したい場合に、Promiseでどのように実装していくかについて学びました。

手続き的な書き方から、逐次処理を行う関数を定義するところまで見ていき、
Promiseであっても関数に処理を分けるという基本的なことは変わらないことを示しました。

Promiseで書くとPromise chainを繋げすぎて縦に長い処理を書いてしまうことがあります。

そんな時は基本に振り返り、処理を関数に分けることで全体の見通しを良くすることは大切です。

また、Promiseのコンストラクタ関数や `then` 等は高階関数なので、
処理を関数に分けておくと組み合わせが行い易いという副次的な効果もあるため、意識してみるといいかもしれません。

[NOTE]
高階関数とは引数に関数オブジェクトを受け取る関数のこと
