[[promise-done]]
== Promise.prototype.done とは何か?

既存のPromise実装ライブラリを利用したことがある人は、
`then` の代わりに使う `done` というメソッドを見たことがあるかもしれません。

それらのライブラリでは `Promise.prototype.done` というような実装が存在し、
使い方は`then`と同じですが、promiseオブジェクトを返さないようになっています。

`Promise.prototype.done` は、<<es6-promises,ES6 Promises>>や<<promises-aplus,Promises/A+>>の仕様には
存在していない記述ですが、多くのライブラリが実装しています。

このセクションでは、`Promise.prototype.done`とは何か?
また何故このようなメソッドが多くのライブラリで実装されているかについて学んでいきましょう。

=== doneを使ったコード例

実際にdoneを使ったコードを見てみると`done`の挙動が分かりやすいと思います。

[source,js]
[[promise-done-example.js]]
.promise-done-example.js
----
include::embed/embed-promise-done-example.js[]
----

最初に述べたように、`Promise.prototype.done`は仕様としては存在しないため、
利用する際は実装されているライブラリを使うか自分で実装する必要があります。

実装については後で解説しますが、まずは`then`を使った場合と`done`を使ったものを比較してみます。

[source,js]
.thenを使った場合
----
var promise = Promise.resolve();
promise.then(function () {
    JSON.parse("this is not json");
}).catch(function (error) {
    console.error(error);// => "SyntaxError: JSON.parse: unexpected keyword at line 1 column 1 of the JSON data"
});
----


比べて見ると以下のような違いがあることが分かります。

* `done` はpromiseオブジェクトを返さない
** つまり、doneの後に`catch`等のメソッドチェーンはできない
* `done` の中で発生したエラーはそのまま外に例外として投げられる
** つまり、Promiseによるエラーハンドリングが行われない

`done` はpromiseオブジェクトを返していないので、
Promise chainの最後になるメソッドというのはわかると思います。

また、Promiseには強力なエラーハンドリング機能があると紹介していましたが、
`done` の中ではそのエラーハンドリングをワザと突き抜けて例外を出すようになっています。

何故このようなPromiseの機能とは相反するメソッドが、多くのライブラリで実装されいるかについては
次のようなPromiseの失敗例を見ていくと分かるかもしれません。

=== 沈黙したエラー

Promiseには強力なエラーハンドリング機能がありますが、
(デバッグツールが上手く働かない場合に)
この機能がヒューマンエラーをより複雑なものにしてしまう一面があります。

これは、<<then-or-catch,then or catch?>>でも同様の内容が出てきたことを覚えているかもしれません。

次のような、promiseオブジェクトを返す関数を考えてみましょう。

[source,js]
[[json-promise.js]]
.json-promise.js
----
include::embed/embed-json-promise.js[]
----

渡された値を`JSON.parse`してpromiseオブジェクトを返す関数ですね。

以下のように使うことができ、`JSON.parse`はパースに失敗すると例外を投げるので、
それを`catch`することが出来ます。

[source,js]
----
var string = "jsonではない文字列";
JSONPromise(string).then(function (object) {
    console.log(object);
}).catch(function(error){
    // => JSON.parseで例外が発生した時
});
----

ちゃんと`catch`していれば何も問題がないのですが、その処理を忘れてしまうというミスを
した時にどこでエラーが発生してるのかわからなくなるというヒューマンエラーを助長させる面があります。

[source,js]
.catchによるエラーハンドリングを忘れてしまった場合
----
var string = "jsonではない文字列";
JSONPromise(string).then(function (object) {
    console.log(object);
}); // <1>
----
<1> 例外が投げられても何も処理されない

`JSON.parse`のような分かりやすい例の場合はまだ良いですが、
メソッドをtypoしたことによるSyntax Errorなどはより深刻な問題となりやすいです。

[source,js]
.typoによるエラー
----
var string = "{}";
JSONPromise(string).then(function (object) {
    conosle.log(object);// <1>
});
----
<1> conosle というtypoがある

この場合は、`console`を`conosle`とtypoしているため、以下のようなエラーが発生するはずです。

> ReferenceError: conosle is not defined

しかし、Promiseではtry-catchされるため、エラーが握りつぶされてしまうという現象が発生しやすくなります。
毎回、正しく`catch`の処理を書くことが出来る場合は何も問題ありませんが、
Promiseの実装によってはこのようなミスが検知しにくくなるケースがあることを知っておくべきでしょう。

このようなエラーの握りつぶしは__unhandled rejection__と言われることがあります。
Rejectedされた時の処理がないというそのままの意味ですね。

[NOTE]
====
このunhandled rejectionが検知しにくい問題はPromiseの実装に依存します。
例えば、 https://github.com/yahoo/ypromise[ypromise] はunhandled rejectionがある場合は、その事をコンソールに表示します。

> Promise rejected but no error handlers were registered to it

また、 https://github.com/petkaantonov/bluebird[Bluebird] の場合も、
明らかに人間のミスにみえるReferenceErrorの場合などはそのままコンソールにエラーを表示してくれます。

> "Possibly unhandled ReferenceError. conosle is not defined

ネイティブのPromiseの場合も同様にこの問題への対処としてGC-based unhandled rejection trackingというものが
搭載されつつあります。

これはpromiseオブジェクトがガーベッジコレクションによって回収されるときに、
それがunhandled rejectionであるなら、エラー表示をするという仕組みがベースとなっているようです。

https://twitter.com/domenic/status/461154989856264192[Firefox] や https://code.google.com/p/v8/issues/detail?id=3093[Chrome] のネイティブPromiseでは一部実装されています。
====

=== doneの実装

Promiseにおける `done` は先程のエラーの握りつぶしを避けるにはどうするかという方法論として、
そもそもエラーハンドリングをしなければいい という豪快な解決方法を提供するメソッドです。

`done`はPromiseの上に実装することが出来るので、
`Promise.prototype.done`というPromiseのprototype拡張として実装してみましょう。

[source,js]
[[promise-prototype-done.js]]
.promise-prototype-done.js
----
include::lib/promise-prototype-done.js[]
----

setTimeoutの中でthrowをすることで、外へそのまま例外を投げることを利用しています。

[source,js]
.setTimeoutのコールバック内ではの例外
----
try{
    setTimeout(function callback() {
        throw new Error("error");// <1>
    }, 0);
}catch(error){
    console.error(error);
}
----
<1> この例外はキャッチすること出来ない

[NOTE]
====
なぜ非同期の`callback`内での例外をキャッチ出来ないのかは以下が参考なります。

- http://techblog.yahoo.co.jp/programming/javascript_error/[JavaScriptと非同期のエラー処理 - Yahoo! JAPAN Tech Blog]
====

<<promise-prototype-done.js,`Promise.prototype.done`>> をよく見てみると、何も`return`していないこともわかると思います。
つまり、`done`は「ここでPromise chainは終了して、例外が起きた場合はそのままpromiseの外へ投げ直す」という処理になっています。

実装や環境がしっかり対応していれば、__unhandled rejection__の検知はできるため、必ずしも`done`が必要というわけではなく、
また今回の<<promise-prototype-done.js,`Promise.prototype.done`>>のように、`done`は既存のPromiseの上に実装することができため、
<<es6-promises,ES6 Promises>>の仕様そのものには入らなかったと言えるかもしれません。

[NOTE]
今回の`Promise.prototype.done`の実装は https://www.promisejs.org/[promisejs.org] を参考にしています。

=== まとめ

このセクションでは、 https://github.com/kriskowal/q/wiki/API-Reference#promisedoneonfulfilled-onrejected-onprogress[Q] や https://github.com/petkaantonov/bluebird[Bluebird] や https://github.com/cscott/prfun#promisedone--undefined[prfun] 等
多くのPromiseライブラリで実装されている`done`の基礎的な実装と、`then`とはどのような違いがあるかについて学びました。

`done`には2つの側面があることがわかりました。

* `done`の中で起きたエラーは外へ例外として投げ直す
* Promise chain を終了するという宣言

<<then-or-catch,then or catch?>> と同様にPromiseにより沈黙してしまったエラーについては、
デバッグツールやライブラリの改善等で殆どのケースでは問題ではなくなるかもしれません。

また、`done`は値を返さない事でそれ以上Promise chainを繋げる事ができなくなるため、
そのような統一感を持たせるという用途で`done`を使うことも出来ます。

<<es6-promises,ES6 Promises>> では根本に用意されてる機能はあまり多くありません。
そのため、自ら拡張したり、拡張したライブラリ等を利用するケースが多いと思います。

その時でも何でもやり過ぎると、せっかく非同期処理をPromiseでまとめても複雑化してしまう場合があるため、
統一感を持たせるというのは抽象的なオブジェクトであるPromiseにおいては大事な部分と言えるかもしれません。
