== Promise.raceとdelayによるXHRのキャンセル

このセクションでは<<promise-race,2章>>で紹介した<<Promise.race,`Promise.race`>>のユースケースとして、
Promise.raceを使ったタイムアウトの実装を学んでいきます。

XHRはもちろん https://developer.mozilla.org/ja/docs/XMLHttpRequest/Synchronous_and_Asynchronous_Requests[timeout] プロパティを持っているので、
これを利用すると簡単に出来ますが、複数のXHRを束ねたタイムアウトや他の機能でも応用が効くため、
分かりやすい非同期処理であるXHRのタイムアウトによるキャンセルを例にしています。

=== Promiseで一定時間待つ

まずはタイムアウトをPromiseでどう実装するかを見て行きたいと思います。

タイムアウトというのは一定時間経ったら何かするという処理なので、`setTimtout`を使えばいいことが分かりますね。

まずは単純に`setTimeout`をPromiseでラップした関数を作ってみましょう。

[source,js]
[[delayPromise.js]]
.delayPromise.js
----
include::embed/embed-delayPromise.js[]
----

`delayPromise(ms)` は引数で指定した時間後にonFulfilledを呼ぶpromiseオブジェクトを返すので、
通常の`setTimeout`を直接使ったものと比較すると以下のように書けるだけの違いです。

[source,js]
----
setTimeout(function () {
    alert("100ms 経ったよ!");
}, 100);
// == ほぼ同様の動作
delayPromise(100).then(function () {
    alert("100ms 経ったよ!");
});
----

ここでは**promiseオブジェクト**であるという事が重要になってくるので覚えておいて下さい。

=== Promise.raceでタイムアウト

`Promise.race`について簡単に振り返ると、
以下のようにどれか一つでもpromiseオブジェクトが解決状態になったら次の処理を実行する静的メソッドでした。

[source,js]
----
include::../Ch2_HowToWrite/embed/embed-promise-race-other.js[]
----

先ほどの<<delayPromise.js,delayPromise>>と別のpromiseオブジェクトを、
`Promise.race`によって競争させることで簡単にタイムアウトが実装出来ます。

[source,js]
[[simple-timeoutPromise.js]]
.simple-timeoutPromise.js
----
include::embed/embed-simple-timeoutPromise.js[]
----

`timeoutPromise(比較対象のpromise, ms)` はタイムアウト処理を入れたい
promiseオブジェクトとタイムアウトの時間を受け取り、`Promise.race`により競争させたpromiseオブジェクトを返します。

`timeoutPromise` を使うことで以下のようにタイムアウト処理を書くことが出来るようになります。

[source,js]
----
var taskPromise = new Promise(function(resolve){
    // 何かの処理
    var result = "...";
    resolve(result);
});
timeoutPromise(taskPromise, 1000).then(function(value){
    // taskPromiseが時間内に終わった
}).catch(function(error){
    // タイムアウトになってしまった
});
----

