[[async-function]]
== Async Functionとは

Async Functionとは非同期処理を行う関数を定義する構文です。
Async Functionは通常の関数とは異なり、必ず``Promise``インスタンスを返す関数を定義する構文です。

Async Functionは次のように関数の前に``async``をつけることで定義できます。
この``doAsync``関数は常に``Promise``インスタンスを返します。

[role="executable"]
[source,javascript]
----
async function doAsync() {
    return "値";
}
// doAsync関数はPromiseを返す
doAsync().then(function(value){
    console.log(value); // => "値"
});
----

Async Functionでは``return``した値の代わりに、``Promise.resolve(返り値)``のように返り値をラップした``Promise``インスタンスを返します。
そのため、このAsync Functionは次のように書いた場合と同じ意味になります。

[role="executable"]
[source,javascript]
----
// 通常の関数でPromiseインスタンスを返している
function doAsync() {
    return Promise.resolve("値");
}
doAsync().then(function(value){
    console.log(value); // => "値"
});
----

またAsync Function内では``await``式というPromiseの非同期処理が完了するまで待つ構文が利用できます。
``await``式を使うことで非同期処理を同期処理のように扱えるため、Promiseチェーンで実現していた処理の流れを読みやすくかけます。

まずは、Async Functionと``await``式を使った場合はどのように書けるかを簡単に見ていきます。

次の例では https://developer.mozilla.org/ja/docs/Web/API/Fetch_API[Fetch API] で``/json/book.json``を取得して、``title``を取り出す``getBookTitle``関数の実行結果をコンソールに出力しています。
Fetch APIはURLのリソースを取得し、Promiseを返す関数です。

この時、取得できる``/json/book.json``は次のような内容になっています。

[[book.json]]
./json/book.json
[source,json]
----
include::../json/book.json[]
----

まずは、Promise APIを使って``fetchBookTitle``関数で取得したタイトルをコンソールに出力してみます。

[role="executable"]
[doctest-state="disabled"]
[source,javascript]
----
function fetchBookTitle(){
    // Fetch APIは指定URLのリソースを取得しPromiseを返す関数
    return fetch("https://azu.github.io/promises-book/json/book.json").then(function(res){
        return res.json(); // レスポンスをJSON形式としてパースする
    }).then(function(json){
        return json.title; // JSONからtitleプロパティを取り出す
    });
}

function main(){
    fetchBookTitle().then(function(title){
        console.log(title); // => "JavaScript Promiseの本"
    });
}

main();
----

次は同様の処理をAsync Functionと``await``式で書いています。
Promise APIを使っていた場合に比べて、コールバック関数がなくなっていることが分かります。

[role="executable"]
[doctest-state="disabled"]
[source,javascript]
----
// `async`をつけて`fetchBookTitle`関数をAsync Functionとして定義
async function fetchBookTitle(){
    // リクエストしてリソースを取得する
    const res = await fetch("https://azu.github.io/promises-book/json/book.json");
    // レスポンスをJSON形式としてパースする
    const json = await res.json();
    // JSONからtitleプロパティを取り出す
    return json.title;
}

// `async`をつけて`main`関数をAsync Functionとして定義
async function main(){
    // `await`式で`fetchBookTitle`の非同期処理が完了するまで待つ
    // `fetchBookTitle`がresolveした値が返り値になる
    const title = await fetchBookTitle();
    console.log(title); // => "JavaScript Promiseの本"
}

main();
----

Async FunctionではPromiseの状態が変化するまで待つ``await``式という機能を利用できます。
Promiseでは結果を``then``メソッドのコールバック関数で取得していたのが、``await``式の右辺にあるPromiseのresolveされた値が左辺の変数へと代入されます。そのため、Async Functionと``await``式を使うことで非同期処理をまるで同期処理のように書けます。

この章では、このAsync Functionと``await``式について詳しく見ていきます。

重要なこととしてAsync FunctionはPromiseの上に作られた構文です。
そのためAsync Functionを理解するには、Promiseを理解する必要があることに注意してください。
