name: deploy
on: [push, pull_request]
permissions:
  contents: write
jobs:
  deploy:
    name: "Build and Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          submodules: recursive # for _tools/fopub/
      - name: setup Node.js
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: 18
      - name: setup Ruby
        uses: ruby/setup-ruby@13e7a03dc3ac6c3798f4570bfead2aed4d96abfb # v1.244.0
        with:
          ruby-version: 2.6
      - name: setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: reitzig/actions-asciidoctor@7570212ae20b63653481675fb1ff62d1073632b0 # v2.0.0
      - name: Install
        run: yarn install && bundle install --path vendor/bundle
      - name: Build
        run: |
          make html
          make pdf
          "./_tools/check-to-deploy.sh"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          exclude_assets: '.github,**/.gitignore,node_modules,.bundle,.netlify,_tools' # .gitignoreを無視する
